export const facilityManagementData: any = {
  data: [
    {
      id: '12332',
      facilityName: 'Atria Tamarac Florida',
      facilityCode: 'ATRFL001',
      cityAndState: 'Newburyport, MA',
      phone: '2738263628',
      agent: 'James Daniel',
      residents: 2,
    },
    {
      id: '12332kujh',
      facilityName: 'Atria Countryside Florida',
      facilityCode: 'ATRFL001',
      cityAndState: 'Newburyport, MA',
      phone: '2738263628',
      agent: 'James Daniel',
      residents: 2,
    },
    {
      id: '1233efe',
      facilityName: 'Atria Countryside Florida',
      facilityCode: 'ATRFL001',
      cityAndState: 'Newburyport, MA',
      phone: '2738263628',
      agent: 'James Daniel',
      residents: 2,
    },
    {
      id: '123erf32',
      facilityName: 'Atria Tamarac Florida',
      facilityCode: 'ATRFL001',
      cityAndState: 'Newburyport, MA',
      phone: '2738263628',
      agent: 'James Daniel',
      residents: 2,
    },
    {
      id: '12erf332',
      facilityName: 'Atria Tamarac Florida',
      facilityCode: 'ATRFL001',
      cityAndState: 'Newburyport, MA',
      phone: '2738263628',
      agent: 'James Daniel',
      residents: 2,
    },
    {
      id: '123tyh32',
      facilityName: 'Atria Tamarac Florida',
      facilityCode: 'ATRFL001',
      cityAndState: 'Newburyport, MA',
      phone: '2738263628',
      agent: 'James Daniel',
      residents: 2,
    },
    {
      id: '12yh332',
      facilityName: 'Atria Tamarac Florida',
      facilityCode: 'ATRFL001',
      cityAndState: 'Newburyport, MA',
      phone: '2738263628',
      agent: 'James Daniel',
      residents: 2,
    },
    {
      id: '123r56y32',
      facilityName: 'Atria Countryside Florida',
      facilityCode: 'ATRFL001',
      cityAndState: 'Newburyport, MA',
      phone: '2738263628',
      agent: 'James Daniel',
      residents: 2,
    },
    {
      id: '123e5tye32',
      facilityName: 'Atria Tamarac Florida',
      facilityCode: 'ATRFL001',
      cityAndState: 'Newburyport, MA',
      phone: '2738263628',
      agent: 'James Daniel',
      residents: 2,
    },
    {
      id: '12e46332',
      facilityName: 'Atria Countryside Florida',
      facilityCode: 'ATRFL001',
      cityAndState: 'Newburyport, MA',
      phone: '2738263628',
      agent: 'James Daniel',
      residents: 2,
    },
  ],
  lastEvaluatedKey: 'test facility',
};
