export const MedicalConditionForm = [
  {
    name: `Alzheimer's Disease`,
    label: "Alzheimer's Disease",
    checkbox: true,
    checked: false,
  },
  {
    name: 'Amyotrophic Lateral Sclerosis (ALS)',
    label: 'Amyotrophic Lateral Sclerosis (ALS)',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Arrhythmia of the Heart',
    label: 'Arrhythmia of the Heart',
    checkbox: true,
    checked: false,
  },

  {
    name: 'Arthritis',
    label: 'Arthritis',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Atrial Fibrillation',
    label: 'Atrial Fibrillation',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Autism',
    label: 'Autism',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Bedsores (pressure ulcers)',
    label: 'Bedsores (pressure ulcers)',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Bipolar Disorder',
    label: 'Bipolar Disorder',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Blindness/Vision Loss',
    label: 'Blindness/Vision Loss',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Cancer',
    label: 'Cancer',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Cardiovascular Disease',
    label: 'Cardiovascular Disease',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Cataracts',
    label: 'Cataracts',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Cholesterol',
    label: 'Cholesterol',
    checkbox: true,
    checked: false,
  },
  {
    name: 'COPD',
    label: 'COPD',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Deafness/Hearing Loss',
    label: 'Deafness/Hearing Loss',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Dementia, Vasular',
    label: 'Dementia, Vasular',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Depression/Loneliness',
    label: 'Depression/Loneliness',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Diabetes',
    label: 'Diabetes',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Fibromyalgia',
    label: 'Fibromyalgia',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Glaucoma',
    label: 'Glaucoma',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Heart Disease',
    label: 'Heart Disease',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Hepatitis',
    label: 'Hepatitis',
    checkbox: true,
    checked: false,
  },
  {
    name: 'High Blood Pressure/Hypertension',
    label: 'High Blood Pressure/Hypertension',
    checkbox: true,
    checked: false,
  },
  {
    name: 'High Cholesterol',
    label: 'High Cholesterol',
    checkbox: true,
    checked: false,
  },
  {
    name: 'HIV/AIDS',
    label: 'HIV/AIDS',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Hyperthyroidism (overactive thyroid)',
    label: 'Hyperthyroidism (overactive thyroid)',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Hypothyroidism (underactive thyroid)',
    label: 'Hypothyroidism (underactive thyroid)',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Incontinence, Urinary',
    label: 'Incontinence, Urinary',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Inflammatory Bowel Disease (IBD)',
    label: 'Inflammatory Bowel Disease (IBD)',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Influenza',
    label: 'Influenza',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Irritable Bowel Syndrome (IBS)',
    label: 'Irritable Bowel Syndrome (IBS)',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Kidney Disease/Failure',
    label: 'Kidney Disease/Failure',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Liver Failure, Acute',
    label: 'Liver Failure, Acute',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Liver Spots (Age Spots)',
    label: 'Liver Spots (Age Spots)',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Lupus',
    label: 'Lupus',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Lymphoma',
    label: 'Lymphoma',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Macular Degeneration',
    label: 'Macular Degeneration',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Melanoma, Skin Cancer',
    label: 'Melanoma, Skin Cancer',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Multiple Sclerosis (MS)',
    label: 'Multiple Sclerosis (MS)',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Obesity',
    label: 'Obesity',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Osteoarthritis',
    label: 'Osteoarthritis',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Pancreatic Cancer',
    label: 'Pancreatic Cancer',
    checkbox: true,
    checked: false,
  },
  {
    name: `Parkinson's Disease`,
    label: "Parkinson's Disease",
    checkbox: true,
    checked: false,
  },

  {
    name: 'Periodontitis',
    label: 'Periodontitis',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Pneumonia',
    label: 'Pneumonia',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Post-traumatic stress disorder (PTSD)',
    label: 'Post-traumatic stress disorder (PTSD)',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Prostate Enlarged',
    label: 'Prostate Enlarged',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Respiratory/Lung Disease',
    label: 'Respiratory/Lung Disease',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Risk of Falling',
    label: 'Risk of Falling',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Sleep Disorder, Apnea, Obstructive',
    label: 'Sleep Disorder, Apnea, Obstructive',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Speech Disorders',
    label: 'Speech Disorders',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Staph Infections',
    label: 'Staph Infections',
    checkbox: true,
    checked: false,
  },
  {
    name: "STD's",
    label: "STD's",
    checkbox: true,
    checked: false,
  },
  {
    name: 'Thrush, Oral',
    label: 'Thrush, Oral',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Transient Ischemic Attack (TIA)',
    label: 'Transient Ischemic Attack (TIA)',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Tuberculosis (TB)',
    label: 'Tuberculosis (TB)',
    checkbox: true,
    checked: false,
  },
  {
    name: 'Ulcerative Colitis',
    label: 'Ulcerative Colitis',
    checkbox: true,
    checked: false,
  },

  {
    name: 'extra',
    options: [
      {
        name: 'other_medical_name',
        autocomplete: true,
        label: 'Other Medical condition(s)',
      },
      {
        button: true,
        isDropDown: true,
      },
    ],
  },
];

export const ActivityForm = [
  {
    name: 'telephone',
    label: '1. Can you use the telephone?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help'],
  },
  {
    name: 'walk',
    label: '2. Can you get to places that are out of walking distance?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help', 'Unable to Walk'],
  },
  {
    name: 'groceries',
    label: '3. Can you go shopping for groceries or other needed items?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help', 'Unable to Shop'],
  },
  {
    name: 'meal',
    label: '4. Can you prepare your own meals?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help'],
  },
  {
    name: 'housework',
    label: '5. Can you do your own housework?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help'],
  },
  {
    name: 'handyman',
    label: '6. Can you do your own handyman/home housework  work?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help'],
  },
  {
    name: 'laundry',
    label: '7. Can you do your own laundry?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help'],
  },
  {
    name: 'medications',
    label: '8a. Do you use any medications?',
    menu: true,
    menuItems: ['Yes', 'No'],
  },
  {
    name: 'medicationown',
    label: '8b. Do you take your own medication? ',
    menu: true,
    menuItems: ['Without Help', 'With Some Help'],
  },

  {
    name: 'medicationy',
    label: '8c. If you had to take medication, could you do it?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help'],
  },
  {
    name: 'money',
    label: '9. Can you manage your own money?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help'],
  },
  {
    name: 'walkown',
    label: '10. Can you walk on your own?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help', 'Unable to Walk'],
  },
  {
    name: 'dress',
    label: '11. Can you dress yourself?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help'],
  },
  {
    name: 'groom',
    label: '12. Can you groom yourself?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help'],
  },
  {
    name: 'bath',
    label: '13. Can you bath yourself?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help'],
  },
  {
    name: 'toilet',
    label: '14. Can you use the toilet?',
    menu: true,
    menuItems: ['Without Help', 'With Some Help'],
  },
  {
    blank: true,
  },
];
