export const FETCHING_LOGIN_DETAILS = 'FETCHING_LOGIN_DETAILS';
export const FETCHING_LOGIN_DETAILS_DONE = 'FETCHING_LOGIN_DETAILS_DONE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const OPEN_TIMEOUT_MODEL = 'OPEN_TIMEOUT_MODEL';
export const CLOSE_TIMEOUT_MODEL = 'CLOSE_TIMEOUT_MODEL';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const CLEAR_REDUX_STATE = 'CLEAR_REDUX_STATE';
